name: Stella VSLAM Docker Build

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run_unit_tests:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run code test suite
        run: |
          chmod +x ./test.py
          echo "===== Testing started ====="
          ./test.py
          echo "===== Testing finished ====="

  dockerize:
    runs-on: self-hosted
    needs: run_unit_tests
    if: success()
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=stella-{{version}}
            type=semver,pattern=stella-{{major}}.{{minor}}

      - name: Login to Github Container registry
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set number of threads
        run: echo "NUM_THREADS=$(expr $(nproc) - 1)" >> $GITHUB_ENV

      - name: Docker Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.stella
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            NUM_THREADS=${{ env.NUM_THREADS }}
